//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransaction
    {
        public int Id { get; set; }
        public Nullable<int> BorrowerId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<System.DateTime> ItemBorrowingDate { get; set; }
        public Nullable<System.DateTime> ItemReturningDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Borrower Borrower { get; set; }
        public virtual Item Item { get; set; }
    }
}
